version: '3.8'

services:
  docs-site:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gracepl-docs
    restart: unless-stopped
    ports:
      - "8000:8000"
    # Không cần Database hay Redis vì đây là Trang Web Tĩnh
